#!/bin/bash

# Set variables
PROJECT_NAME="war-frontend"
PROFILE_ENV="main"
BASE_DIR="/home/mf/apps/frontend"
PROJECT_DIR="${BASE_DIR}/${PROJECT_NAME}"
DIST_DIR="${PROJECT_DIR}/dist"
PORT=12389
NEXUS_URL="https://repo.qikongjian.com/repository/frontend-tar-files/"
NEXUS_USER="admin"
NEXUS_PASS="YZ9Gq6=8\*G|?:,"
CONTAINER_NAME="${PROJECT_NAME}-container-${PROFILE_ENV}"
IMAGE_NAME="${PROJECT_NAME}:${PROFILE_ENV}"

# Create directories
mkdir -p $PROJECT_DIR
mkdir -p $DIST_DIR
echo "Setting deployment directory to $PROJECT_DIR for the ${PROFILE_ENV} environment."

# Stop and remove existing container
if [ $(docker ps -a -q -f name=^/${CONTAINER_NAME}$) ]; then
    echo "Container $CONTAINER_NAME already exists, stopping..."
    docker stop $CONTAINER_NAME
    echo "Removing existing container..."
    docker rm $CONTAINER_NAME
fi

# Download and extract the tar file
echo "Downloading tar file from Nexus..."
curl -u "${NEXUS_USER}:${NEXUS_PASS}" -O "${NEXUS_URL}/${PROJECT_NAME}-${PROFILE_ENV}.tar.gz"
if [ $? -ne 0 ]; then
    echo "Failed to download tar file from Nexus"
    exit 1
fi

echo "Extracting tar file..."
tar -xzvf "${PROJECT_NAME}-${PROFILE_ENV}.tar.gz" -C "$DIST_DIR" --strip-components=1
if [ $? -ne 0 ]; then
    echo "Failed to extract tar file"
    exit 1
fi

# Create Dockerfile in the project directory
cat > $PROJECT_DIR/Dockerfile << EOF
FROM node:20.19.0-alpine

WORKDIR /app

# Copy package.json and package-lock.json
COPY dist/package*.json ./

# Install dependencies
RUN yarn install --production --registry=https://registry.npmmirror.com

# Copy the rest of the application
COPY dist .

ENV NODE_ENV=production

EXPOSE 3000

CMD ["yarn", "start"]
EOF

# Build Docker image
echo "Building Docker image..."
docker build -t $IMAGE_NAME $PROJECT_DIR
if [ $? -ne 0 ]; then
    echo "Failed to build Docker image"
    exit 1
fi

# Run the new container
echo "Starting new container..."
docker run -d \
  -p $PORT:3000 \
  --name $CONTAINER_NAME \
  --restart unless-stopped \
  $IMAGE_NAME

if [ $? -ne 0 ]; then
    echo "Failed to start new container"
    exit 1
fi

# Clean up
echo "Cleaning up..."
#rm "${PROJECT_NAME}-${PROFILE_ENV}.tar.gz"

# 清理未使用的镜像
docker image prune -a -f
echo "Deployment completed at $(date)"
